# Generated by Django 2.2 on 2019-09-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=60, verbose_name='Location')),
                ('diameter', models.CharField(max_length=60, null=True, verbose_name='Diameter')),
                ('angle', models.FloatField(null=True, verbose_name='Angle')),
                ('material', models.CharField(choices=[('high-density polyethylene', 'HDPE'), ('polyvinyl chloride', 'PVC'), ('clay', 'CLY'), ('concrete', 'CNCRT'), ('Steel', 'STL')], max_length=60, verbose_name='Material')),
                ('elevation', models.FloatField(null=True, verbose_name='Elevation')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.FloatField(null=True, verbose_name='Reading History')),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrainMonit.Pipe')),
            ],
        ),
    ]
