# Generated by Django 2.2 on 2019-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrainMonit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='id_name',
            field=models.CharField(max_length=60, null=True, verbose_name='ID Name'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='location',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], max_length=60, verbose_name='Location'),
        ),
    ]
