# Generated by Django 2.2 on 2019-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrainMonit', '0002_auto_20190929_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='velocity',
            field=models.FloatField(null=True, verbose_name='Velocity'),
        ),
    ]
